# Generated by Django 5.2.7 on 2025-11-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchamodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
